### ISSUE TITLE
I can't open up the GUI app on mac.

### ISSUE THREAD

**Issue by omagarwal25** [amarcolini/joos#13]
There doesn't seem to be a clear way of running the app. I unzipped and went into ./bin and ran ./gui.sh after running chmod on both the ./java file and the ./gui.sh file. Any idea why this isn't working? This is the stack trace that I got.

```
WARNING: package javafx.scene not in javafx.graphics
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.tk.quantum.QuantumToolkit.init(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.tk.Toolkit.getToolkit(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.tk.Toolkit.getToolkit(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at com.amarcolini.joos.merged.module@0.4.3-alpha/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)```

**Comment by amarcolini** [comment]
Try [this image](https://ufile.io/h5gsccp8). gui.sh in the bin folder is the application launcher, but I'm not entirely sure how to fix the problem.

**Comment by omagarwal25** [comment]
It works.

**Comment by omagarwal25** [comment]
Also is there an option for smaller robots? Or is that not a feature yet?

**Comment by amarcolini** [comment]
Not yet!
